Rewrite as composite action
Signed-off-by: Paul Meyer <49727155+katexochen@users.noreply.github.com>

diff --git a/.github/workflows/test-integration.yml b/.github/workflows/test-integration.yml
--- a/.github/workflows/test-integration.yml
+++ b/.github/workflows/test-integration.yml
@@ -1,4 +1,4 @@
-name: Integration tests
+name: integration test
 
 on:
   push:
@@ -13,12 +13,56 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
 
-      - name: Set up Go
-        uses: actions/setup-go@v3
+      - name: Setup Go
+        uses: actions/setup-go@v2
         with:
-          go-version-file: go.mod
+          go-version: "1.20"
 
-      - name: Run integration tests
-        run: go test -v ./...
-        env:
-          INTEGRATION_TEST: "true"
+      - name: Run action on tidy module
+        uses: ./
+        with:
+          modules: ./testdata/tidy/module3
+
+      - name: Run action on untidy module
+        id: should-fail-1
+        continue-on-error: true
+        uses: ./
+        with:
+          modules: ./testdata/untidy/module2
+
+      - name: Check previous step failed
+        if: steps.should-fail-1.outcome != 'failure'
+        shell: bash
+        run: |
+          echo "Previous step should have failed"
+          exit 1
+
+      - name: Run action on untidy module with submodules
+        id: should-fail-2
+        continue-on-error: true
+        uses: ./
+        with:
+          modules: ./testdata/untidy/module1
+          submodules: true
+
+      - name: Check previous step failed
+        if: steps.should-fail-2.outcome != 'failure'
+        shell: bash
+        run: |
+          echo "Previous step should have failed"
+          exit 1
+
+      - name: Run action on untidy module with submodules and go.work
+        id: should-fail-3
+        continue-on-error: true
+        uses: ./
+        with:
+          modules: ./testdata/untidy/module3
+          submodules: true
+
+      - name: Check previous step failed
+        if: steps.should-fail-3.outcome != 'failure'
+        shell: bash
+        run: |
+          echo "Previous step should have failed"
+          exit 1
diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,16 +1,76 @@
 name: go-tidy-check
-author: katexochen
+author: Paul Meyer (katexochen)
 description: go-tidy-check checks if your modules are tidy.
+branding:
+  icon: check
+  color: blue
+
 inputs:
   modules:
     description: Path(s) of the modules to check. Separate multiple paths with space. Current working dir is used if empty.
     required: false
+  submodules:
+    description: |
+      Whether to check submodules. Default is false. If there is a go.work file, the submodules of the workspace are checked.
+      Otherwise the action searches subdirectories for go.mod files and checks them.
+    required: false
+
 runs:
-  using: docker
-  image: docker://ghcr.io/katexochen/go-tidy-check:v1.0.2
-  args:
-    - -d
-    - ${{ inputs.modules }}
-branding:
-  icon: check
-  color: blue
+  using: composite
+  steps:
+    - name: Execute tidy-check script
+      shell: bash
+      env:
+        INPUTS_MODULES: ${{ inputs.modules }}
+        INPUTS_SUBMODULES: ${{ inputs.submodules }}
+      run: |
+        if [[ "${INPUTS_SUBMODULES}" == "true" ]]; then
+          checkSubmodules=true
+        fi
+
+        if ! git diff --exit-code --quiet; then
+          echo "Working directory is not clean, please commit or stash changes"
+          exit 1
+        fi
+
+        version=$(go version)
+        if [[ "${version}" != *"go1.20"* ]]; then
+          echo "Go version must be 1.20 or higher"
+          exit 1
+        fi
+
+        if [[ -z "${INPUTS_MODULES}" ]]; then
+          echo "No modules specified, checking current working directory"
+          topLevelModules=$(pwd)
+        else
+          echo "Modules specified in input: ${INPUTS_MODULES}"
+          topLevelModules="${INPUTS_MODULES}"
+        fi
+
+        allModules="${topLevelModules}"
+
+        if [[ "${checkSubmodules}" == true ]]; then
+          echo "Listing submodules"
+          for module in ${topLevelModules}; do
+            echo "Listing submodules of $module"
+
+            if [[ -f "$module/go.work" ]]; then
+              echo "go.work file found, using workspace"
+              subModules=$(go list -f '{{.Dir}}' -m)
+              allModules="${allModules} ${subModules}"
+            else
+              echo "go.work file not found, searching subdirectories"
+              subModules=$(find . -name go.mod -exec sh -c 'dirname $1 | xargs realpath' shell {} \;)
+              allModules="${allModules} ${subModules}"
+            fi
+          done
+        else
+          echo "Submodules not checked"
+        fi
+
+        for module in ${allModules}; do
+          echo "Checking module $module"
+          go mod tidy -C "$module"
+        done
+
+        git diff --exit-code
